# python and sudo are required for closure linter:
# `sudo python setup.py install`
language: python
sudo: required
script:
  - ./build/jslint.sh
  - ./build/jsmin.sh
before_install:
  - git submodule update --init --recursive
  - mkdir /home/travis/build/Datamart/Greylock/src/glize
  - cp /home/travis/build/Datamart/Greylock/glize/src /home/travis/build/Datamart/Greylock/src/glize
